import {
  NIGHT_OPENING as ROSENTHAL_NIGHT_OPENING,
  PROLOGUE as ROSENTHAL_PROLOGUE,
} from "../data/rosenthalContent.js";

// 프롤로그와 밤 진입 본문은 rosenthalContent.js만 수정 원본으로 둔다.
// 이 파일은 화면용 메타데이터와 화자 매핑만 가진다.
export const PROLOGUE = {
  tag: "프롤로그",
  title: "들리지 않는 목소리",
  text: ROSENTHAL_PROLOGUE,
  speakers: [
    "narration",
    "player",
    "player",
    "player",
    "player",
    "narration",
    "narration",
    "npc:maid",
    "narration",
    "narration",
    "narration",
    "player",
    "player",
    "player",
    "player",
  ],
};

export const DAY_OPENING_SCRIPT = [
  {
    speaker: "npc:scribe",
    text: "오늘 처리하실 일을 정리했습니다. 처음 보시는 항목부터 설명드리겠습니다.",
  },
  {
    speaker: "narration",
    text: "당신이 아무것도 모른다는 사실을, 그는 조금도 이상하게 여기지 않는다.",
  },
];

export const DAY_PERIODS = ["오전", "오후", "저녁"];

export const DAY_INTERLUDES = [
  {
    tag: "오전이 지나간다",
    title: "해는 아직 높다.",
    paragraphs: [
      "당신은 선택을 해야 한다. 그 뒤에 무엇이 기다리고 있을지는 아무도 알려주지 않는다.",
      "그래도 태양이 떠 있는 동안에는 괜찮을 것 같다.",
      "불어오는 바람은 산뜻하고, 사람들의 웃음 소리가 주변을 가득 채운다.",
      "분명, 잘못된 결정도 내일 고치면 될 것이다.",
      "……그렇게 믿는다.",
    ],
    button: "오후의 일을 시작한다",
  },
  {
    tag: "오후",
    title: "영지는 평화롭다.",
    paragraphs: [
      "소설 속에서 몇 번이나 본 듯한, 판에 박힌 영지다. 그것도 드물 만큼 평화로운 곳이다.",
      "시장에는 먹을 것이 넉넉하고, 골목에는 악취가 나지 않는다.",
      "병사는 주민에게 시비를 걸지 않고, 상인은 값을 속이기보다 장부를 먼저 보여준다.",
      "점심에는 갓 구운 빵과 따뜻한 수프가 나왔고, 누구도 접시를 빼앗거나 음식에 독이 들었는지 의심하지 않았다.",
      "사람들은 최소한의 상식을 지키며, 도움을 청하는 일도 무너진 담장이나 부족한 물자처럼 손을 대면 해결할 수 있는 것뿐이다. 내가 아는 상식에서 벗어나는 일은 아직 하나도 일어나지 않았다.",
      "혹시 정말로, 영지를 돌보며 살아가는 힐링물 같은 세계인 걸까?",
    ],
    button: "저녁의 일을 시작한다",
  },
  {
    tag: "저녁",
    title: "해가 기울기 시작한다.",
    paragraphs: [
      "저녁 무렵, 오늘 만난 사람들은 차례로 일을 마쳤다고 보고한다. 메이드는 커튼을 닫고, 서기관은 장부를 거두며, 복도의 촛불은 일정한 간격으로 하나씩 켜진다.",
      "누구도 서두르지 않지만 움직임에는 망설임이 없다. 마치 당신만 모르는 저녁의 순서가 오래전부터 정해져 있었던 것 같다.",
      "마지막 햇빛이 창틀 아래로 사라질 때까지, 아무 일도 일어나지 않는다.",
    ],
    button: "해가 지는 것을 지켜본다",
  },
];

export const ENDINGS = {
  peacefulLord: {
    tag: "엔딩 · 닫힌 지하실",
    title: "정식 영주",
    subtitle: "당신은 이 영지에서 살아가는 방법을 배웠다.",
    paragraphs: [
      "일곱 번째 밤에도 당신은 지하로 내려가지 않았다. 문 두드리는 소리는 새벽이 오기 전에 스스로 멎었다.",
      "그동안 장부는 한 번도 바닥나지 않았고, 영지의 어느 항목도 영 아래로 떨어지지 않았다. 사람들은 당신의 결정을 신중함이라 불렀고, 마침내 정식 영주로 인정했다.",
      "당신이라면 이 영지의 비밀을 풀어헤치지 않고도 살아갈 방법을 알고 있다. 닫힌 문은 열지 않고, 들리지 말아야 할 소리는 듣지 않은 채, 사람들에게 필요한 결정을 내리면 된다.",
      "그렇게 오래도록 평화롭게 살 수 있을지도 모른다.",
      "……그렇지만, 그게 정답인지는 모른다.",
    ],
  },
};

export const NIGHT_ENTRY_SCRIPT = [
  { speaker: "npc:maid", text: ROSENTHAL_NIGHT_OPENING[0] },
  { speaker: "npc:maid", text: ROSENTHAL_NIGHT_OPENING[1] },
  { speaker: "npc:maid", text: ROSENTHAL_NIGHT_OPENING[2] },
];

export const DAY_ACTIONS = [
  {
    id: "documents",
    title: "서류를 검토한다",
    tone: "neutral",
    weight: 8,
    npcId: "서기관",
    affinities: { 서기관: 1 },
    traits: { record: 3, suspicion: 1 },
    stats: { insight: 1, stamina: -2 },
    resources: { silver: 2 },
    estate: { recordIntegrity: 3, stability: 1 },
    unlocks: ["scribe"],
    result: "서류 형식은 낯설다. 하지만 서명할 곳은 알아볼 수 있다. 서기관은 별다른 질문 없이 다음 장을 내민다.",
  },
  {
    id: "training-yard",
    title: "기사 훈련장을 방문한다",
    tone: "neutral",
    weight: 8,
    npcId: "기사",
    affinities: { 기사: 1 },
    traits: { knight: 3, execution: 1 },
    stats: { health: 1, resolve: 1, stamina: -3 },
    estate: { stability: 2, trust: 1 },
    unlocks: ["knight", "sword"],
    result: "기사들은 훈련 보고를 마치고 지시를 기다린다. 당신이 한마디 하자 오후 훈련 방식이 바뀐다.",
  },
  {
    id: "mansion-map",
    title: "메이드에게 저택의 구조를 묻는다",
    tone: "neutral",
    weight: 8,
    npcId: "메이드",
    affinities: { 메이드: 1 },
    traits: { mansion: 3, suspicion: 1 },
    stats: { insight: 1, stamina: -2 },
    estate: { corruption: 1, trust: 1 },
    unlocks: ["maid"],
    result: "메이드는 방과 복도를 차례로 설명한다. 지하로 내려가는 길만 자연스럽게 건너뛴다.",
  },
  {
    id: "merchant-supplies",
    title: "상인과 물자 거래를 확인한다",
    tone: "neutral",
    weight: 7,
    npcId: "상인",
    affinities: { 상인: 1 },
    traits: { trade: 3, shortcut: 1 },
    stats: { charm: 1, stamina: -2 },
    resources: { food: 3, silver: 2 },
    estate: { trust: 1 },
    unlocks: ["merchant"],
    result: "상인은 물자의 값과 수량을 차례로 말한다. 장부를 확인한 뒤 부족한 물자를 더 들여오기로 한다.",
  },
  {
    id: "estate-repairs",
    title: "잡부들과 영지 시설을 점검한다",
    tone: "neutral",
    weight: 7,
    npcId: "잡부",
    affinities: { 잡부: 1 },
    traits: { life: 3, record: 1 },
    stats: { health: 1, stamina: -4 },
    resources: { timber: -2, food: 1 },
    estate: { stability: 2, trust: 3 },
    unlocks: ["worker"],
    result: "무너진 담장과 새는 지붕은 실제로 고쳐진다. 잡부들은 당신이 자신들의 이름을 몰라도 개의치 않는다.",
  },
  {
    id: "alchemy-room",
    title: "연금술사의 작업실을 방문한다",
    tone: "extreme",
    weight: 6,
    traits: { shortcut: 3, suspicion: 1 },
    stats: { insight: 2, faith: -1, stamina: -3 },
    heresy: true,
    resources: { silver: 2, fear: 1 },
    estate: { corruption: 2 },
    unlocks: ["alchemist"],
    result: "연금술사는 작업대 위의 병들을 보여준다. 이름표가 없는 병 하나는 끝내 설명하지 않는다.",
  },
  {
    id: "old-doll-room",
    title: "오래된 인형이 보관된 방을 조사한다",
    tone: "extreme",
    weight: 5,
    traits: { exorcism: 3, suspicion: 2 },
    stats: { faith: 1, insight: 1, stamina: -3 },
    divineBonus: true,
    resources: { fear: 2 },
    estate: { corruption: 1 },
    unlocks: ["doll"],
    result: "인형은 악한 것을 쫓아낸다고 적혀 있다. 누가 적었는지는 남아 있지 않다.",
  },
  {
    id: "armory",
    title: "무기고를 확인한다",
    tone: "neutral",
    weight: 6,
    traits: { execution: 3, knight: 2 },
    stats: { resolve: 1, stamina: -3 },
    estate: { stability: 1 },
    unlocks: ["sword"],
    result: "검 한 자루가 다른 무기보다 쉽게 뽑힌다. 손잡이에는 오래된 손자국이 남아 있다.",
  },
  {
    id: "chapel-scripture",
    title: "예배실의 성서를 살핀다",
    tone: "extreme",
    weight: 5,
    traits: { divine: 3, exorcism: 1 },
    stats: { faith: 2, stamina: -2 },
    divineBonus: true,
    resources: { faith: 3 },
    estate: { corruption: 1 },
    unlocks: ["scripture"],
    result: "성서는 잘 관리되어 있다. 마지막 장의 한 구절만 여러 번 읽힌 흔적이 있다.",
  },
  {
    id: "observe",
    title: "아무것도 하지 않고 관찰한다",
    tone: "neutral",
    weight: 5,
    traits: { suspicion: 3, mansion: 1 },
    stats: { insight: 1, stamina: -1 },
    estate: { recordIntegrity: 1 },
    unlocks: ["barehand"],
    result: "당신이 아무 지시도 하지 않자 사람들은 잠시 멈춘다. 곧, 원래 정해져 있던 순서대로 다시 움직인다.",
  },
];

export const NIGHT_CHOICES = [
  {
    id: "knight",
    title: "기사와 내려간다",
    kind: "person",
    target: "기사",
    tone: "danger",
    weight: 8,
    traits: { knight: 6, execution: 2 },
    stats: { resolve: 1, stamina: -3 },
    estate: { stability: -2, missing: 1 },
    event: "target-lost",
    result: "지하에서 돌아온 사람은 당신뿐이다. 기사가 들고 간 방패는 마지막 계단 아래에 남아 있다.",
  },
  {
    id: "scribe",
    title: "서기관과 내려간다",
    kind: "person",
    target: "서기관",
    tone: "danger",
    weight: 8,
    traits: { record: 6, suspicion: 2 },
    stats: { insight: 1, stamina: -3 },
    estate: { recordIntegrity: -4, missing: 1 },
    event: "target-lost",
    result: "서기관은 마지막 문 앞에서 장부를 펼쳤다. 돌아온 장부의 마지막 줄에는 당신의 이름만 적혀 있다.",
  },
  {
    id: "maid",
    title: "메이드와 내려간다",
    kind: "person",
    target: "메이드",
    tone: "danger",
    weight: 8,
    traits: { mansion: 6, suspicion: 2 },
    stats: { insight: 1, stamina: -3 },
    estate: { trust: -2, missing: 1, corruption: 2 },
    event: "target-lost",
    result: "메이드는 마지막 계단에서 익숙한 복도를 발견했다며 먼저 걸어갔다. 당신만 저택으로 돌아왔다.",
  },
  {
    id: "merchant",
    title: "상인과 내려간다",
    kind: "person",
    target: "상인",
    tone: "danger",
    weight: 7,
    traits: { trade: 6, shortcut: 2 },
    stats: { charm: 1, stamina: -3 },
    resources: { silver: 8, fear: 2 },
    estate: { trust: -3, missing: 1 },
    event: "target-lost",
    result: "상인은 마지막 문 앞에 은화를 내려놓았다. 문이 열린 뒤 상인은 보이지 않았다.",
  },
  {
    id: "worker",
    title: "잡부와 내려간다",
    kind: "person",
    target: "잡부",
    tone: "danger",
    weight: 7,
    traits: { life: 6, record: 1 },
    stats: { health: 1, stamina: -3 },
    estate: { trust: -4, missing: 1 },
    event: "target-lost",
    result: "잡부는 돌아오지 않았다. 돌아오는 동안, 당신은 그의 이름을 한 번도 부르지 않았다는 사실을 깨닫는다.",
  },
  {
    id: "alchemist",
    title: "연금술사와 내려간다",
    kind: "person",
    target: "연금술사",
    tone: "extreme",
    weight: 6,
    traits: { shortcut: 6, suspicion: 2 },
    stats: { insight: 2, faith: -2, stamina: -4 },
    heresy: true,
    resources: { silver: 6, fear: 3 },
    estate: { corruption: 6, missing: 1 },
    event: "target-lost",
    result: "연금술사가 만든 약으로 문은 열렸다. 돌아오는 길에는 빈 약병만 남아 있었다.",
  },
  {
    id: "doll",
    title: "악한 것을 쫓아낸다는 인형과 내려간다",
    kind: "item",
    target: "오래된 인형",
    tone: "extreme",
    weight: 5,
    traits: { exorcism: 6, suspicion: 2 },
    stats: { faith: 1, stamina: -3 },
    divineBonus: true,
    resources: { fear: 3 },
    estate: { corruption: 4 },
    event: "item-lost",
    result: "인형을 문 앞에 놓자 두드리는 소리가 멎었다. 문이 사라진 뒤 인형도 찾을 수 없었다.",
  },
  {
    id: "sword",
    title: "검을 들고 내려간다",
    kind: "item",
    target: "검",
    tone: "lethal",
    weight: 5,
    traits: { execution: 7, knight: 2 },
    stats: { health: -3, resolve: 1, stamina: -4 },
    resources: { fear: 4 },
    estate: { stability: 1, corruption: 2 },
    event: "physical-damage",
    result: "당신은 혼자 돌아왔다. 검날은 검게 변했고 닦아도 원래 색으로 돌아오지 않았다.",
  },
  {
    id: "barehand",
    title: "맨손으로 내려간다",
    kind: "self",
    target: null,
    tone: "lethal",
    weight: 3,
    requires: { suspicion: 3, life: 3 },
    traits: { suspicion: 6, life: 4 },
    stats: { health: -6, insight: 2, stamina: -5 },
    resources: { fear: 8 },
    estate: { corruption: 7, stability: -3 },
    event: "physical-damage",
    result: "당신은 맨손으로 돌아왔다. 손바닥에는 내려가기 전까지 없었던 문양이 남아 있다.",
  },
  {
    id: "scripture",
    title: "성서를 들고 내려간다",
    kind: "item",
    target: "성서의 마지막 구절",
    tone: "extreme",
    weight: 5,
    traits: { divine: 7, exorcism: 2 },
    stats: { faith: 2, stamina: -3 },
    divineBonus: true,
    resources: { faith: 4, fear: 2 },
    estate: { corruption: 3 },
    event: "item-lost",
    result: "성서를 펼치자 문이 닫혔다. 돌아온 뒤 성서의 마지막 구절이 사라져 있었다.",
  },
];

export const WORKER_NAME_CHOICES = [
  {
    id: "remember-worker",
    title: "기억한다",
    tone: "neutral",
    traits: { life: 3, record: 2 },
    stats: { insight: 1 },
    estate: { trust: 2, recordIntegrity: 2 },
    result: "당신은 그 이름을 말한다. 아무도 대답하지 않지만, 이름은 사라지지 않는다.",
  },
  {
    id: "forget-worker",
    title: "기억하지 못한다",
    tone: "neutral",
    traits: { execution: 2, suspicion: 1 },
    stats: { resolve: 1 },
    estate: { trust: -3, recordIntegrity: -2 },
    result: "당신은 대답하지 못한다. 메이드는 더 묻지 않는다.",
  },
];

export const FORFEIT_RESULTS = {
  day: "결정을 미루는 동안 다른 사람들이 대신 정했다. 당신의 의자만 비어 있었다.",
  night: "아무도 고르지 못한 채 계단 앞에 오래 서 있었다. 아침이 되자 손목에 검은 자국이 생겨 있었다.",
};
